/**
 * Copy Phase 5 static UI into frontend/public for Vercel (standard static root).
 * Writes `phase6-api-origin.js` so the browser can call Railway directly (avoids Vercel serverless 504 on long /query).
 * Set `RAILWAY_API_URL` in Vercel (build + runtime) to the Railway HTTPS origin.
 */
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const frontendRoot = path.join(__dirname, "..");
const dest = path.join(frontendRoot, "public");
const srcDir = path.join(frontendRoot, "..", "src", "phase5", "public");

/**
 * @param {string | undefined} raw
 * @returns {string}
 */
function normalizeApiOrigin(raw) {
  let s = (raw || "").trim();
  if (!s) return "";
  s = s.replace(/\/+$/, "");
  if (!/^https?:\/\//i.test(s)) {
    s = `https://${s}`;
  }
  return s;
}

async function pathExists(p) {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

async function copyRecursive(from, to) {
  await fs.mkdir(to, { recursive: true });
  const entries = await fs.readdir(from, { withFileTypes: true });
  for (const ent of entries) {
    const fp = path.join(from, ent.name);
    const tp = path.join(to, ent.name);
    if (ent.isDirectory()) {
      await copyRecursive(fp, tp);
    } else if (ent.isFile()) {
      await fs.copyFile(fp, tp);
    }
  }
}

if (!(await pathExists(srcDir))) {
  console.error(`sync-public: missing source ${srcDir}`);
  process.exit(1);
}

await fs.rm(dest, { recursive: true, force: true });
await copyRecursive(srcDir, dest);

const apiOrigin = normalizeApiOrigin(process.env.RAILWAY_API_URL);
const originSnippet = `// Generated by sync-public.mjs - do not edit.\nwindow.__PHASE6_API_ORIGIN__ = ${JSON.stringify(apiOrigin)};\n`;
await fs.writeFile(path.join(dest, "phase6-api-origin.js"), originSnippet, "utf8");
console.log(
  `sync-public: ${srcDir} -> ${dest}; phase6-api-origin.js -> ${apiOrigin ? `${apiOrigin} (browser → Railway)` : "(empty → same origin)"}`,
);

